networks:
  default:
    driver: 'bridge'

volumes:
  pg_data:
  backend_config:

services:
  postgres:
    container_name: 'backend-database'
    image: 'postgres:15.3'
    environment:
      - 'POSTGRES_PASSWORD=backend'
      - 'POSTGRES_USER=backend'
      - 'POSTGRES_DB=backend'
    volumes:
      - 'pg_data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  backend:
    container_name: 'backend'
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    depends_on:
      - 'postgres'
    ports:
      - '8080:8080'
    volumes:
      - 'backend_config:/app/config'
    networks:
      - 'default'
